CREATE DATABASE IF NOT EXISTS `auth`;
CREATE DATABASE IF NOT EXISTS `chat`;
CREATE DATABASE IF NOT EXISTS `photos`;

CREATE DATABASE IF NOT EXISTS `auth_test`;
CREATE DATABASE IF NOT EXISTS `chat_test`;
CREATE DATABASE IF NOT EXISTS `photos_test`;

GRANT ALL PRIVILEGES ON *.* TO 'indeedadmin'@'%';