CREATE DATABASE IF NOT EXISTS `auth`;
CREATE DATABASE IF NOT EXISTS `restaurant`;
CREATE DATABASE IF NOT EXISTS `customer`;
CREATE DATABASE IF NOT EXISTS `order`;

CREATE DATABASE IF NOT EXISTS `auth_test`;
CREATE DATABASE IF NOT EXISTS `restaurant_test`;
CREATE DATABASE IF NOT EXISTS `customer_test`;
CREATE DATABASE IF NOT EXISTS `order_test`;

GRANT ALL PRIVILEGES ON *.* TO 'uberadmin'@'%';